// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/proto/forgepb/forge.proto

package forgepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,3,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_forgepb_forge_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *TaskRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_forgepb_forge_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusRequest) Reset() {
	*x = TaskStatusRequest{}
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusRequest) ProtoMessage() {}

func (x *TaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusRequest.ProtoReflect.Descriptor instead.
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_forgepb_forge_proto_rawDescGZIP(), []int{2}
}

func (x *TaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	RetryCount     int32                  `protobuf:"varint,3,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	AssignedWorker string                 `protobuf:"bytes,4,opt,name=assigned_worker,json=assignedWorker,proto3" json:"assigned_worker,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskStatusResponse) Reset() {
	*x = TaskStatusResponse{}
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusResponse) ProtoMessage() {}

func (x *TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_forgepb_forge_proto_rawDescGZIP(), []int{3}
}

func (x *TaskStatusResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskStatusResponse) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *TaskStatusResponse) GetAssignedWorker() string {
	if x != nil {
		return x.AssignedWorker
	}
	return ""
}

func (x *TaskStatusResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TaskStatusResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type WorkerHeartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerId       string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Capabilities   []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	AvailableSlots int32                  `protobuf:"varint,3,opt,name=available_slots,json=availableSlots,proto3" json:"available_slots,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkerHeartbeat) Reset() {
	*x = WorkerHeartbeat{}
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHeartbeat) ProtoMessage() {}

func (x *WorkerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHeartbeat.ProtoReflect.Descriptor instead.
func (*WorkerHeartbeat) Descriptor() ([]byte, []int) {
	return file_internal_proto_forgepb_forge_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerHeartbeat) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerHeartbeat) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *WorkerHeartbeat) GetAvailableSlots() int32 {
	if x != nil {
		return x.AvailableSlots
	}
	return 0
}

type TaskAssignment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_internal_proto_forgepb_forge_proto_rawDescGZIP(), []int{5}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskAssignment) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskAssignment) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Result        []byte                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_forgepb_forge_proto_rawDescGZIP(), []int{6}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type TaskResultAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultAck) Reset() {
	*x = TaskResultAck{}
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultAck) ProtoMessage() {}

func (x *TaskResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultAck.ProtoReflect.Descriptor instead.
func (*TaskResultAck) Descriptor() ([]byte, []int) {
	return file_internal_proto_forgepb_forge_proto_rawDescGZIP(), []int{7}
}

func (x *TaskResultAck) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type WatchTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	PollIntervalMs int32                  `protobuf:"varint,2,opt,name=poll_interval_ms,json=pollIntervalMs,proto3" json:"poll_interval_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchTaskRequest) Reset() {
	*x = WatchTaskRequest{}
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTaskRequest) ProtoMessage() {}

func (x *WatchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTaskRequest.ProtoReflect.Descriptor instead.
func (*WatchTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_forgepb_forge_proto_rawDescGZIP(), []int{8}
}

func (x *WatchTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WatchTaskRequest) GetPollIntervalMs() int32 {
	if x != nil {
		return x.PollIntervalMs
	}
	return 0
}

type ClusterInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfoRequest) Reset() {
	*x = ClusterInfoRequest{}
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfoRequest) ProtoMessage() {}

func (x *ClusterInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfoRequest.ProtoReflect.Descriptor instead.
func (*ClusterInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_forgepb_forge_proto_rawDescGZIP(), []int{9}
}

type ClusterInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderAddress string                 `protobuf:"bytes,1,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Nodes         []*NodeInfo            `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfoResponse) Reset() {
	*x = ClusterInfoResponse{}
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfoResponse) ProtoMessage() {}

func (x *ClusterInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfoResponse.ProtoReflect.Descriptor instead.
func (*ClusterInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_forgepb_forge_proto_rawDescGZIP(), []int{10}
}

func (x *ClusterInfoResponse) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

func (x *ClusterInfoResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *ClusterInfoResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_forgepb_forge_proto_rawDescGZIP(), []int{11}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  string                 `protobuf:"bytes,1,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_forgepb_forge_proto_rawDescGZIP(), []int{12}
}

func (x *ListTasksRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskStatusResponse  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_forgepb_forge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_forgepb_forge_proto_rawDescGZIP(), []int{13}
}

func (x *ListTasksResponse) GetTasks() []*TaskStatusResponse {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_internal_proto_forgepb_forge_proto protoreflect.FileDescriptor

const file_internal_proto_forgepb_forge_proto_rawDesc = "" +
	"\n" +
	"\"internal/proto/forgepb/forge.proto\x12\x05forge\"\x85\x01\n" +
	"\vTaskRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1f\n" +
	"\vmax_retries\x18\x03 \x01(\x05R\n" +
	"maxRetries\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\"?\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\",\n" +
	"\x11TaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xcd\x01\n" +
	"\x12TaskStatusResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vretry_count\x18\x03 \x01(\x05R\n" +
	"retryCount\x12'\n" +
	"\x0fassigned_worker\x18\x04 \x01(\tR\x0eassignedWorker\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"{\n" +
	"\x0fWorkerHeartbeat\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12'\n" +
	"\x0favailable_slots\x18\x03 \x01(\x05R\x0eavailableSlots\"\x80\x01\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\"\x99\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06result\x18\x04 \x01(\fR\x06result\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"3\n" +
	"\rTaskResultAck\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"U\n" +
	"\x10WatchTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12(\n" +
	"\x10poll_interval_ms\x18\x02 \x01(\x05R\x0epollIntervalMs\"\x14\n" +
	"\x12ClusterInfoRequest\"\x80\x01\n" +
	"\x13ClusterInfoResponse\x12%\n" +
	"\x0eleader_address\x18\x01 \x01(\tR\rleaderAddress\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12%\n" +
	"\x05nodes\x18\x03 \x03(\v2\x0f.forge.NodeInfoR\x05nodes\"J\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"7\n" +
	"\x10ListTasksRequest\x12#\n" +
	"\rstatus_filter\x18\x01 \x01(\tR\fstatusFilter\"D\n" +
	"\x11ListTasksResponse\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x19.forge.TaskStatusResponseR\x05tasks2\xdb\x03\n" +
	"\x0eForgeScheduler\x125\n" +
	"\n" +
	"SubmitTask\x12\x12.forge.TaskRequest\x1a\x13.forge.TaskResponse\x12D\n" +
	"\rGetTaskStatus\x12\x18.forge.TaskStatusRequest\x1a\x19.forge.TaskStatusResponse\x12C\n" +
	"\x0eRegisterWorker\x12\x16.forge.WorkerHeartbeat\x1a\x15.forge.TaskAssignment(\x010\x01\x12;\n" +
	"\x10ReportTaskResult\x12\x11.forge.TaskResult\x1a\x14.forge.TaskResultAck\x12A\n" +
	"\tWatchTask\x12\x17.forge.WatchTaskRequest\x1a\x19.forge.TaskStatusResponse0\x01\x12G\n" +
	"\x0eGetClusterInfo\x12\x19.forge.ClusterInfoRequest\x1a\x1a.forge.ClusterInfoResponse\x12>\n" +
	"\tListTasks\x12\x17.forge.ListTasksRequest\x1a\x18.forge.ListTasksResponseB2Z0github.com/Ritpra93/forge/internal/proto/forgepbb\x06proto3"

var (
	file_internal_proto_forgepb_forge_proto_rawDescOnce sync.Once
	file_internal_proto_forgepb_forge_proto_rawDescData []byte
)

func file_internal_proto_forgepb_forge_proto_rawDescGZIP() []byte {
	file_internal_proto_forgepb_forge_proto_rawDescOnce.Do(func() {
		file_internal_proto_forgepb_forge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_forgepb_forge_proto_rawDesc), len(file_internal_proto_forgepb_forge_proto_rawDesc)))
	})
	return file_internal_proto_forgepb_forge_proto_rawDescData
}

var file_internal_proto_forgepb_forge_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_proto_forgepb_forge_proto_goTypes = []any{
	(*TaskRequest)(nil),         // 0: forge.TaskRequest
	(*TaskResponse)(nil),        // 1: forge.TaskResponse
	(*TaskStatusRequest)(nil),   // 2: forge.TaskStatusRequest
	(*TaskStatusResponse)(nil),  // 3: forge.TaskStatusResponse
	(*WorkerHeartbeat)(nil),     // 4: forge.WorkerHeartbeat
	(*TaskAssignment)(nil),      // 5: forge.TaskAssignment
	(*TaskResult)(nil),          // 6: forge.TaskResult
	(*TaskResultAck)(nil),       // 7: forge.TaskResultAck
	(*WatchTaskRequest)(nil),    // 8: forge.WatchTaskRequest
	(*ClusterInfoRequest)(nil),  // 9: forge.ClusterInfoRequest
	(*ClusterInfoResponse)(nil), // 10: forge.ClusterInfoResponse
	(*NodeInfo)(nil),            // 11: forge.NodeInfo
	(*ListTasksRequest)(nil),    // 12: forge.ListTasksRequest
	(*ListTasksResponse)(nil),   // 13: forge.ListTasksResponse
}
var file_internal_proto_forgepb_forge_proto_depIdxs = []int32{
	11, // 0: forge.ClusterInfoResponse.nodes:type_name -> forge.NodeInfo
	3,  // 1: forge.ListTasksResponse.tasks:type_name -> forge.TaskStatusResponse
	0,  // 2: forge.ForgeScheduler.SubmitTask:input_type -> forge.TaskRequest
	2,  // 3: forge.ForgeScheduler.GetTaskStatus:input_type -> forge.TaskStatusRequest
	4,  // 4: forge.ForgeScheduler.RegisterWorker:input_type -> forge.WorkerHeartbeat
	6,  // 5: forge.ForgeScheduler.ReportTaskResult:input_type -> forge.TaskResult
	8,  // 6: forge.ForgeScheduler.WatchTask:input_type -> forge.WatchTaskRequest
	9,  // 7: forge.ForgeScheduler.GetClusterInfo:input_type -> forge.ClusterInfoRequest
	12, // 8: forge.ForgeScheduler.ListTasks:input_type -> forge.ListTasksRequest
	1,  // 9: forge.ForgeScheduler.SubmitTask:output_type -> forge.TaskResponse
	3,  // 10: forge.ForgeScheduler.GetTaskStatus:output_type -> forge.TaskStatusResponse
	5,  // 11: forge.ForgeScheduler.RegisterWorker:output_type -> forge.TaskAssignment
	7,  // 12: forge.ForgeScheduler.ReportTaskResult:output_type -> forge.TaskResultAck
	3,  // 13: forge.ForgeScheduler.WatchTask:output_type -> forge.TaskStatusResponse
	10, // 14: forge.ForgeScheduler.GetClusterInfo:output_type -> forge.ClusterInfoResponse
	13, // 15: forge.ForgeScheduler.ListTasks:output_type -> forge.ListTasksResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_forgepb_forge_proto_init() }
func file_internal_proto_forgepb_forge_proto_init() {
	if File_internal_proto_forgepb_forge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_forgepb_forge_proto_rawDesc), len(file_internal_proto_forgepb_forge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_forgepb_forge_proto_goTypes,
		DependencyIndexes: file_internal_proto_forgepb_forge_proto_depIdxs,
		MessageInfos:      file_internal_proto_forgepb_forge_proto_msgTypes,
	}.Build()
	File_internal_proto_forgepb_forge_proto = out.File
	file_internal_proto_forgepb_forge_proto_goTypes = nil
	file_internal_proto_forgepb_forge_proto_depIdxs = nil
}
